# Generated by Django 3.0.3 on 2020-03-06 08:13

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thumbnail', models.ImageField(upload_to='thumb/')),
                ('Title', models.CharField(help_text='Nome do post', max_length=255)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Summary', ckeditor.fields.RichTextField()),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
